### PR TITLE
Version 0.1.2 (Repeater fix, Float conversion, CKEditor support)

### PR DESCRIPTION
**Pull request by flipzoom**
Hey Robin, 

you're right. Repeater support didn't work like that with AJAX. Your solution works perfectly. I've adopted it, too. 👍 

But the changes with the decimal point are not correct and do not work. Depending on which local is set, e.g.` setlocale(LC_ALL, 'de_DE.UTF-8');` PHP internally changes the decimal point from a (.) to a (,) AFTER the floats operation. In JavaScript, however, the float number must have a dot (.), otherwise it won't work. This means that without the conversion after the calculation, the value in the JS array will contain `"_1,33333":"4:3"` instead of `"_1.33333":"4:3"`. 

But I've changed my solution for the conversion. I now use `number_format()`, because this kills two birds with one stone. The function also rounds directly and limits the decimal places.

I also noticed that the module does not work with inline images in the CKEditor. The reason is that no "field" parameter is passed in the URL when the editor is opened. I added this feature with this version. The default configuration of the module is used for this. In order not to be redundant, I have outsourced the building of the ratio array to a separate function.

Hope you can do something with the suggestions and changes. :blush: :beers:

### CODE REVIEW

**Comment by Toutouwai** [comment]
Thanks!

I'll defer to you on the decimal issue. Here in NZ these locale issues aren't something I ever need to deal with so I'm not even sure how to test it. I tried `setlocale(LC_ALL, 'de_DE.UTF-8');` in both config and in the Tracy console and it's not giving the results I'd expect, but probably the locale isn't taking effect properly.



I take it that in your environment the code above correctly casts that string to float? If so that's great - I just want to be sure that if users configure the module using comma separators that it works properly.

The cropper for images in a CKE field thing is a pain. I hadn't considered the cropper there because I dislike images being directly embedded in CKE fields so I always disable that feature and deal with images in CKE fields via a custom textformatter module.

I don't want to fall back to the default ratios in the CKE scenario - the ratios need to be those defined for the field the image belongs to, in the context of the template of the page holding the image. I have an idea of how this might be done so I'll come back soon with an update for you to test.

**Comment by Toutouwai** [comment]
@FlipZoomMedia, could you please test the version attached below and let me know if it's working for you? You might need to do a hard refresh in Page Edit after install seeing as the cache-busting is tied to module version number and you already bumped the version to 0.1.2 in your PR.

[ImageCropRatios.zip](https://github.com/Toutouwai/ImageCropRatios/files/4425616/ImageCropRatios.zip)

**Comment by Toutouwai** [comment]
I've pushed this version out now so that I don't forget to do it. But please let me know if you come across any issues with it.

**Comment by flipzoom** [comment]
Hey Robin, 

Sorry for the delay, I finally got to test it and it works perfectly. Good job! The PR can now be closed. 

Best regards 
David

**Comment by Toutouwai** [comment]
Great, thanks for testing!

**Pull request closed without merging**
